name: Build LocalHostPlus

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Fabric Mod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Refresh Dependencies
        run: ./gradlew --refresh-dependencies

      - name: Build
        run: ./gradlew clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: LocalHostPlus
          path: build/libs/*.jar
